### ISSUE TITLE
Couldn't download all files of IELTS 

### ISSUE THREAD

**Issue by venkatanarsimha** [croton007/magoosh_downloader#1]
Hi @croton007 ,

Download of IELTS files got stopped in between because of the below error. Can you please check and update the code or something else so that all files get downloaded without any errors?
Many thanks in advance :)

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "Magoosh_Downloader.py", line 44, in <lambda>
  File "Magoosh_Downloader.py", line 14, in test
  File "functions.py", line 28, in Total_Download
  File "functions.py", line 91, in Download_Videos
  File "urllib\request.py", line 257, in urlretrieve
FileNotFoundError: [Errno 2] No such file or directory: '8-True/False/Not Given and Yes/No/Not Given Questions.mp4'

Regards,
Venkat

**Comment by croton007** [comment]
I apologize for the inconvenience, there was a bug in my code which I have resolved. Now download the latest version from my Github link

**Comment by venkatanarsimha** [comment]
Hi @croton007 ,

Thanks a lot for taking time and fixing the issue. It's working now perfectly.
