### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by sundrb** [croton007/magoosh_downloader#3]
Facing below error

please be patient it may take up to 1hr to download
downloading 24-folders
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "Magoosh_Downloader.py", line 109, in <lambda>
  File "Magoosh_Downloader.py", line 14, in test
  File "new_code.py", line 15, in download
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'IELTS'
please be patient it may take up to 1hr to download
downloading 24-folders
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "Magoosh_Downloader.py", line 109, in <lambda>
  File "Magoosh_Downloader.py", line 14, in test
  File "new_code.py", line 22, in download
  File "new_app.py", line 19, in download_file_from_google_drive
  File "new_app.py", line 40, in save_response_content
  File "zipfile.py", line 1222, in __init__
  File "zipfile.py", line 1289, in _RealGetContents
zipfile.BadZipFile: File is not a zip file
![image](https://user-images.githubusercontent.com/55596936/90908679-48220000-e3f2-11ea-8ef5-a0823b836e39.png)

**Comment by hemanthreddy-22** [comment]
same issue :
zipfile.BadZipFile: File is not a zip file

Not Working ...
Release Older version
